Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SmartOffice.Data;
using SmartOffice.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Identity;

namespace SmartOffice.Controllers
{
    public class DashboardController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DashboardController(ApplicationDbContext context)
        {
            _context = context;
        }

        public ViewResult Index()
        {
            ClaimsPrincipal currentUser = this.User;
            string idOfCurrentUser = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;
            string roleOfCurrentUser = currentUser.FindFirst(ClaimTypes.Role).Value;

            var allUsers = _context.Users
                .Select(s => new {
                    Names = s.FirstName + " " + s.LastName,
                    Id = s.Id
                })
                .OrderBy(x=> x.Names)
                .ToList();

            ViewBag.AllUsers = allUsers;
            return View();
        }
    }
}

Controllers/TaskReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SmartOffice.Data;
using SmartOffice.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using X.PagedList;
using X.PagedList.Mvc.Core;
using X.PagedList.Mvc;

namespace SmartOffice.Controllers
{
    public class TaskReportController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TaskReportController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: TaskReport
        public ViewResult Index(string searchString, string currentFilter, string sortOrder, int? page)
        {
            //ViewData["currentUserId"] = HttpContext.User.Identity.Name;
            ClaimsPrincipal currentUser = this.User;
            string idOfCurrentUser = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;
            string roleOfCurrentUser = currentUser.FindFirst(ClaimTypes.Role).Value;

            ViewBag.CurrentSort = sortOrder;
            ViewBag.OwnerSortParm = String.IsNullOrEmpty(sortOrder) ? "owner" : "";
            ViewBag.TimeSortParm = sortOrder == "Time" ? "time_desc" : "Time";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var filterReports = from s in _context.TaskReport
                join u in _context.Users on s.OwnerId equals u.Id into User
                from m in User.DefaultIfEmpty()
                select new TaskReport
                {
                    Id = s.Id,
                    OwnerId = s.OwnerId,
                    Activity = s.Activity,
                    TimeIn = s.TimeIn,
                    OwnerInfo = m.FirstName + " " + m.LastName
                };

            var allUsers = _context.Users
                .Select(s => new {
                    Names = s.FirstName + " " + s.LastName,
                    Id = s.Id
                })
                .ToList();
            // Filter reports by creator if current user does not have special access
            if (roleOfCurrentUser != "manager"
                && roleOfCurrentUser != "admin"
                && roleOfCurrentUser != "superuser")
            {
                filterReports = filterReports.Where(s => s.OwnerId.Equals(idOfCurrentUser));
            }

            if (!String.IsNullOrEmpty(searchString))
            {
                string searchId = "";
                foreach (var item in allUsers)
                {
                    if (item.Names == searchString)
                    {
                        searchId = item.Id;
                    }
                }

                filterReports = filterReports.Where(s => s.OwnerId.Contains(searchId));
            }

            switch (sortOrder)
            {
                case "owner":
                    filterReports = filterReports.OrderByDescending(s => s.OwnerId);
                    break;
                case "Time":
                    filterReports = filterReports.OrderBy(s => s.TimeIn);
                    break;
                case "time_desc":
                    filterReports = filterReports.OrderByDescending(s => s.TimeIn);
                    break;
                default:
                    filterReports = filterReports.OrderByDescending(s => s.TimeIn);
                    break;
            }

            ViewData["idOfCurrentUser"] = idOfCurrentUser;

            // Boolean parameter to determine if edit/delete button will display.
            Dictionary<int, string> reviewInfo = new Dictionary<int, string>();

            foreach (var item in filterReports)
            {
                var taskReview = _context.TaskReview
                    .Where(s => s.TaskReportId.Equals(item.Id))
                    .ToList();

                if (taskReview.Count > 0)
                {
                    reviewInfo.Add(item.Id, "true");
                }
                else
                {
                    reviewInfo.Add(item.Id, "false");
                }
            }

            ViewData["reviewInfo"] = reviewInfo;

            int pageSize = 20;
            int pageNumber = (page ?? 1);
            return View(filterReports.ToPagedList(pageNumber, pageSize));

            //return View(await filterReports.ToListAsync());
        }



        // GET: TaskReport/Details/5
        //[Authorize(Roles ="admin,manager")]
        public async Task<IActionResult> Details(int? id)
        {
            ClaimsPrincipal currentUser = this.User;
            string idOfCurrentUser = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;
            string roleOfCurrentUser = currentUser.FindFirst(ClaimTypes.Role).Value;

            if (id == null)
            {
                return NotFound();
            }

            var taskReport = (from s in _context.TaskReport
                join u in _context.Users on s.OwnerId equals u.Id into User
                from m in User.DefaultIfEmpty()
                select new TaskReport
                {
                    Id = s.Id,
                    OwnerId = s.OwnerId,
                    Activity = s.Activity,
                    Achievement = s.Achievement,
                    Comments = s.Comments,
                    TimeIn = s.TimeIn,
                    OwnerInfo = m.FirstName + " " + m.LastName
                })
                .FirstOrDefault(m => m.Id == id);

            if (taskReport == null)
            {
                return NotFound();
            }

            //Deny access if no special access and current user is not the creator; or report has been reviewed.
            var taskReview = await _context.TaskReview
                .Where(s => s.TaskReportId.Equals(taskReport.Id))
                .ToListAsync();

            string editable = "true";
            if (taskReport.OwnerId != idOfCurrentUser
                && roleOfCurrentUser != "manager"
                && roleOfCurrentUser != "admin"
                && roleOfCurrentUser != "superuser")
            {
                return Unauthorized();
            }

            if (taskReport.OwnerId != idOfCurrentUser || taskReview.Count > 0) {
                editable = "false";                
            }

            ViewData["editable"] = editable;
            ViewData["currentUserId"] = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;
            ViewData["currentUserRole"] = currentUser.FindFirst(ClaimTypes.Role).Value;
            
            return View(taskReport);
        }

        // GET: TaskReport/Create
        public IActionResult Create()
        {
            ClaimsPrincipal currentUser = this.User;
            ViewData["currentUserId"] = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;
            return View();
        }

        // POST: TaskReport/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,OwnerId,Activity,Achievement,Comments,TimeIn")] TaskReport taskReport)
        {
            if (ModelState.IsValid)
            {
                _context.Add(taskReport);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(taskReport);
        }

        // GET: TaskReport/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            ClaimsPrincipal currentUser = this.User;
            string idOfCurrentUser = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;

            if (id == null)
            {
                return NotFound();
            }

            var taskReport = await _context.TaskReport.FindAsync(id);
            if (taskReport == null)
            {
                return NotFound();
            }

            // Deny Edit access unless current user is the creator or if reviewed
            var taskReview = await _context.TaskReview
                .Where(s => s.TaskReportId.Equals(taskReport.Id))
                .ToListAsync();

            if (taskReport.OwnerId != idOfCurrentUser || taskReview.Count > 0)
            {
                return Unauthorized();
            }

            return View(taskReport);
        }

        // POST: TaskReport/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,OwnerId,Activity,Achievement,Comments,TimeIn")] TaskReport taskReport)
        {
            ClaimsPrincipal currentUser = this.User;
            string idOfCurrentUser = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;
            string roleOfCurrentUser = currentUser.FindFirst(ClaimTypes.Role).Value;

            if (id != taskReport.Id)
            {
                return NotFound();
            }

            // Deny Edit access unless current user is the creator or if reviewed
            var taskReview = await _context.TaskReview
                .Where(s => s.TaskReportId.Equals(taskReport.Id))
                .ToListAsync();

Controllers/TaskReviewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SmartOffice.Data;
using SmartOffice.Models;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace SmartOffice.Controllers
{
    [Authorize(Roles ="superuser,admin,manager")]
    public class TaskReviewController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TaskReviewController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: TaskReview
        public async Task<IActionResult> Index()
        {

            var reviews = await (from s in _context.TaskReview
                join u in _context.Users on s.OwnerId equals u.Id into User
                from m in User.DefaultIfEmpty()
                join p in _context.TaskReport on s.TaskReportId equals p.Id into Report
                from n in Report.DefaultIfEmpty()
                select new TaskReview
                {
                    Id = s.Id,
                    OwnerId = s.OwnerId,
                    Activity = n.Activity,
                    TimeIn = s.TimeIn,
                    OwnerInfo = m.FirstName + " " + m.LastName
                })
                .ToListAsync();

            return View(reviews);
        }

        // GET: TaskReview/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var taskReview = (from s in _context.TaskReview
                join u in _context.Users on s.OwnerId equals u.Id into User
                from m in User.DefaultIfEmpty()
                join p in _context.TaskReport on s.TaskReportId equals p.Id into Report
                from n in Report.DefaultIfEmpty()
                join w in _context.Users on n.OwnerId equals w.Id into Author
                from r in Author.DefaultIfEmpty()
                select new TaskReview
                {
                    Id = s.Id,
                    OwnerId = s.OwnerId,
                    TimeIn = s.TimeIn,
                    Details = s.Details,
                    Activity = n.Activity,
                    Achievement = n.Achievement,
                    Comments = n.Comments,
                    OwnerInfo = m.FirstName + " " + m.LastName,
                    Author = r.FirstName + " " + r.LastName
                })
                .FirstOrDefault(m => m.Id == id);

            if (taskReview == null)
            {
                return NotFound();
            }

            return View(taskReview);
        }

        // GET: TaskReview/Create
        public IActionResult Create()
        {
            ClaimsPrincipal currentUser = this.User;
            ViewData["currentUserId"] = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;

            return View();
        }

        // POST: TaskReview/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,OwnerId,TaskReportId,Details,TimeIn")] TaskReview taskReview)
        {
            if (ModelState.IsValid)
            {
                _context.Add(taskReview);
                await _context.SaveChangesAsync();
                //return RedirectToAction(actionName: "Details", controllerName: "TaskReport", routeValues: new { id = "TaskReportId" });
                return RedirectToAction(nameof(Index));
            }
            return View(taskReview);
        }

        // GET: TaskReview/Edit/5
        /*
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var taskReview = await _context.TaskReview.FindAsync(id);
            if (taskReview == null)
            {
                return NotFound();
            }
            return View(taskReview);
        }

        // POST: TaskReview/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,OwnerId,TaskReportId,Details,TimeIn")] TaskReview taskReview)
        {
            if (id != taskReview.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(taskReview);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TaskReviewExists(taskReview.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(taskReview);
        }

        // GET: TaskReview/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var taskReview = await _context.TaskReview
                .FirstOrDefaultAsync(m => m.Id == id);
            if (taskReview == null)
            {
                return NotFound();
            }

            return View(taskReview);
        }

        // POST: TaskReview/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var taskReview = await _context.TaskReview.FindAsync(id);
            _context.TaskReview.Remove(taskReview);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        */

        private bool TaskReviewExists(int id)
        {
            return _context.TaskReview.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using System.Security.Claims
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@{
    string roleOfCurrentUser = "";
    string idOfCurrentUser = "";
    string namesOfCurrentUser = "";
    if (SignInManager.IsSignedIn(User))
    {
        ClaimsPrincipal currentUser = this.User;
        roleOfCurrentUser = currentUser.FindFirst(ClaimTypes.Role).Value;
        idOfCurrentUser = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;

        var userInfo = await UserManager.GetUserAsync(User);
        namesOfCurrentUser = userInfo.FirstName + " " + userInfo.LastName;
    }
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
        SmartOffice
        @{
            //ViewData["Title"];
        }
    </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/customStyles.css" />
</head>
<body style="background-color: #FFF;">
    <header id="header">
        <nav id="cnav-bar" class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/media/sm-logo.jpg" height="25" />
                    <span id="capp-title">SmartOffice</span>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (roleOfCurrentUser != "")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="TaskAssignment" asp-action="Index">Assignments</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="TaskReport" asp-action="Index">Reports</a>
                            </li>
                            @if (roleOfCurrentUser == "manager"
                                || roleOfCurrentUser == "admin"
                                || roleOfCurrentUser =="superuser")
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="TaskReview" asp-action="Index">Reviews</a>
                                </li>
                            }
                            @if (roleOfCurrentUser == "admin"
                                || roleOfCurrentUser =="superuser")
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="ApplicationUser" asp-action="Index">User Manager</a>
                                </li>
                            }
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="cflex cmainbar">
        <main role="main" class="pb-3" style="padding: 0 30px 0 50px; width: 100%;">
            @RenderBody()
        </main>
        @if (SignInManager.IsSignedIn(User))
        {
            <div class="cflex csidebar">
                <div id="notifications">
                    notifications
                </div>
                <div id="messaging" class="cflex">
                    <span id="messages-header">Instant Messages</span>
                    <div id="messages-content"></div>
                    <div id="messages-input">
                        <input type="hidden" id="userInput" placeholder="User" value="@namesOfCurrentUser" />
                        <textarea type="text" id="messageInput"></textarea><r/>
                        <input type="button" id="sendButton" class="cbtn cbtn-blue" value="Send Message" />
                    </div>
                </div>
            </div>
        }
        else
        {
            <div
                class="cflex csidebar"
                style="background-color:#222;padding:30px;align-items:center;justify-content:center;">
                 <img src="~/media/logo.png" />
            </div>
        }
    </div>
    <div class="footer">
        &copy; 2021 - SmartOffice by &nbsp;<a href="http://benadegbaju.com.ng" target="_blank">BenniesM</a>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/signalr/dist/browser/signalr.min.js"></script>
    <script src="~/js/chat.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>