Models/TaskAssignment.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SmartOffice.Models
{
    public class TaskAssignment
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "Created by")]
        public string OwnerId { get; set; }

        [Required]
        [Display(Name = "Execution by")]
        public string RunnerId { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        [Display(Name = "Task details")]
        public string Instructions { get; set; }

        [Display(Name = "Time submitted")]
        public DateTime TimeIn { get; set; } = DateTime.Now;

        [Required]
        [Display(Name = "Completion deadline")]
        public DateTime Deadline { get; set; }

        [Display(Name = "Start date")]
        public DateTime? Started { get; set; }

        [Display(Name = "Execution date")]
        public DateTime? Executed { get; set; }

        [Display(Name = "Execution note")]
        public string ExecutedNotes { get; set; }

        [Display(Name = "Completion date")]
        public DateTime? Completed { get; set; }

        [Display(Name = "Completion note")]
        public string CompletionNotes { get; set; }
        
        public string status { get; set; }

        public string Owner;
        public string Runner;
    }
}

Controllers/TaskAssignmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SmartOffice.Data;
using SmartOffice.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Identity;
using X.PagedList;
using X.PagedList.Mvc.Core;
using X.PagedList.Mvc;

namespace SmartOffice.Controllers
{
    public class TaskAssignmentController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TaskAssignmentController(ApplicationDbContext context)
        {
            _context = context;
        }
/*
        class UsersModel
        { 
            public IEnumerable<User> Users { get; set; }
            public string User { get; set;}
        }
*/
        // GET: TaskAssignment
        public ViewResult Index(string searchString, string currentFilter, string sortOrder, int? page)
        {
            ClaimsPrincipal currentUser = this.User;
            string idOfCurrentUser = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;
            string roleOfCurrentUser = currentUser.FindFirst(ClaimTypes.Role).Value;

            ViewBag.CurrentSort = sortOrder;
            ViewBag.RunnerSortParm = String.IsNullOrEmpty(sortOrder) ? "runner" : "";
            ViewBag.DeadlineSortParm = sortOrder == "Deadline" ? "deadline_desc" : "Deadline";
            ViewBag.TimeSortParm = sortOrder == "Time" ? "time_desc" : "Time";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var filterAssignments = from s in _context.TaskAssignment
                join u in _context.Users on s.RunnerId equals u.Id into User
                from m in User.DefaultIfEmpty()
                select new TaskAssignment
                {
                    Id = s.Id,
                    OwnerId = s.OwnerId,
                    RunnerId = s.RunnerId,
                    Title = s.Title,
                    Deadline = s.Deadline,
                    TimeIn = s.TimeIn,
                    status = s.status,
                    Runner = m.FirstName + " " + m.LastName
                };

            // Filter assignments by creator if current user does not have special access
            if (roleOfCurrentUser != "manager"
                && roleOfCurrentUser != "admin"
                && roleOfCurrentUser != "superuser")
            {
                filterAssignments = filterAssignments
                    .Where(s => s.OwnerId.Equals(idOfCurrentUser)
                        || s.RunnerId.Equals(idOfCurrentUser));
            }

            var allUsers = _context.Users
                .Select(s => new {
                    Names = s.FirstName + " " + s.LastName,
                    Id = s.Id
                })
                .ToList();

            if (!String.IsNullOrEmpty(searchString))
            {
                string searchId = "";
                foreach (var item in allUsers)
                {
                    if (item.Names == searchString)
                    {
                        searchId = item.Id;
                    }
                }

                filterAssignments = filterAssignments.Where(s => s.RunnerId.Contains(searchId));
            }

            switch (sortOrder)
            {
                case "runner":
                    filterAssignments = filterAssignments.OrderByDescending(s => s.RunnerId);
                    break;
                case "Deadline":
                    filterAssignments = filterAssignments.OrderBy(s => s.Deadline);
                    break;
                case "deadline_desc":
                    filterAssignments = filterAssignments.OrderByDescending(s => s.Deadline);
                    break;
                case "Time":
                    filterAssignments = filterAssignments.OrderBy(s => s.TimeIn);
                    break;
                case "time_desc":
                    filterAssignments = filterAssignments.OrderByDescending(s => s.TimeIn);
                    break;
                default:
                    filterAssignments = filterAssignments.OrderByDescending(s => s.TimeIn);
                    break;
            }

            ViewData["idOfCurrentUser"] = idOfCurrentUser;

            int pageSize = 20;
            int pageNumber = (page ?? 1);
            return View(filterAssignments.ToPagedList(pageNumber, pageSize));
        }

        // GET: TaskAssignment/Details/5
        public IActionResult Details(int? id)
        {
            ClaimsPrincipal currentUser = this.User;
            string idOfCurrentUser = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;
            string roleOfCurrentUser = currentUser.FindFirst(ClaimTypes.Role).Value;

            if (id == null)
            {
                return NotFound();
            }

            var taskAssignment = (from s in _context.TaskAssignment
                join u in _context.Users on s.OwnerId equals u.Id into User
                from m in User.DefaultIfEmpty()
                join x in _context.Users on s.RunnerId equals x.Id into Runner
                from r in Runner.DefaultIfEmpty()
                select new TaskAssignment
                {
                    Id = s.Id,
                    OwnerId = s.OwnerId,
                    RunnerId = s.RunnerId,
                    Title = s.Title,
                    Instructions = s.Instructions,
                    TimeIn = s.TimeIn,
                    Deadline = s.Deadline,
                    Started = s.Started,
                    Executed = s.Executed,
                    ExecutedNotes = s.ExecutedNotes,
                    Completed = s.Completed,
                    CompletionNotes = s.CompletionNotes,
                    status = s.status,
                    Owner = m.FirstName + " " + m.LastName,
                    Runner = r.FirstName + " " + r.LastName
                })
                .FirstOrDefault(m => m.Id == id);

            if (taskAssignment == null)
            {
                return NotFound();
            }

            if (taskAssignment.OwnerId != idOfCurrentUser
                && taskAssignment.RunnerId != idOfCurrentUser
                && roleOfCurrentUser != "manager"
                && roleOfCurrentUser != "admin"
                && roleOfCurrentUser != "superuser")
            {
                return Unauthorized();
            }

            ViewBag.Editable = true;
            ViewBag.Role = "ordinary";
            if (taskAssignment.OwnerId != idOfCurrentUser
                || taskAssignment.status == "executed"
                || taskAssignment.status == "completed")
            {
                ViewBag.Editable = false;
            }
            if (roleOfCurrentUser == "superuser"
                || roleOfCurrentUser == "admin"
                || roleOfCurrentUser == "manager") 
            {
                ViewBag.Role = "special";
            }

            ViewBag.CurrentUserId = idOfCurrentUser;

            return View(taskAssignment);
        }

        // GET: TaskAssignment/Create
        public IActionResult Create()
        {
/*            var UsersModel = new UsersModel()
            {
                
            };
*/
            var allUsers = _context.Users
            .Select(s => new ApplicationUser {
                FullName = s.FirstName + " " + s.LastName,
                Id = s.Id
            })
            .OrderBy(x => x.FullName)
            .ToList();
            ViewBag.AllUsers = allUsers;

            ClaimsPrincipal currentUser = this.User;
            ViewData["currentUserId"] = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;

            return View();
        }

        // POST: TaskAssignment/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,OwnerId,RunnerId,Title,Instructions,TimeIn,Deadline,Started,Executed,ExecutedNotes,Completed,CompletionNotes,status")] TaskAssignment taskAssignment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(taskAssignment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(taskAssignment);
        }

        // GET: TaskAssignment/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            ClaimsPrincipal currentUser = this.User;
            string idOfCurrentUser = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;

            if (id == null)
            {
                return NotFound();
            }

            var taskAssignment = await _context.TaskAssignment.FindAsync(id);
            if (taskAssignment == null)
            {
                return NotFound();
            }

            if (taskAssignment.OwnerId != idOfCurrentUser
                || taskAssignment.status == "executed"
                || taskAssignment.status == "completed")
            {
                return Unauthorized();
            }

            var allUsers = _context.Users
            .Select(s => new ApplicationUser {
                FullName = s.FirstName + " " + s.LastName,
                Id = s.Id
            })
            .OrderBy(x => x.FullName)
            .ToList();

Views/TaskAssignment/Create.cshtml
@model SmartOffice.Models.TaskAssignment

@{
    ViewData["Title"] = "Create New Assignment";
}

<h4>@ViewData["Title"]</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" style="width: 25%;">
                <input type="hidden" asp-for="OwnerId" class="form-control" value=@ViewData["currentUserId"] />
                <span asp-validation-for="OwnerId" class="text-danger"></span>
            </div>
            <div class="form-group" style="width: 45%;">
                <select asp-for="RunnerId" class="form-control">
                    <option value="">Who will execute this task?</option>
                    @foreach (var user in ViewBag.AllUsers)
                    {
                        <option value=@user.Id>@user.FullName</option>
                    }
                </select>
                <span asp-validation-for="RunnerId" class="text-danger"></span>
            </div>
            <div class="form-group" style="width: 85%;">
                <input asp-for="Title" class="form-control" placeholder="Title" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group" style="width: 85%;">
                <textarea asp-for="Instructions" class="form-control" placeholder="Task details...">
                </textarea>
                <span asp-validation-for="Instructions" class="text-danger"></span>
            </div>
            <div class="form-group" style="width: 45%;">
                <label asp-for="Deadline" class="control-label"></label>
                <input asp-for="Deadline" class="form-control" />
                <span asp-validation-for="Deadline" class="text-danger"></span>
            </div>
            <div class="form-group" style="width: 25%;">
                <input type="hidden" asp-for="status" class="form-control" value="assigned" />
                <span asp-validation-for="status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input class="cbtn cbtn-lemon" type="submit" value="Create Assignment" class="btn btn-primary" />
                <input type="button" class="cbtn cbtn-plain" value="Back to List" onclick="location.href='@Url.Action("Index", "TaskAssignment")'" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/TaskAssignment/Delete.cshtml
@model SmartOffice.Models.TaskAssignment

@{
    ViewData["Title"] = "Delete";
}

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="row" style="padding: 1%;">
        <dt class = "col-sm-3 viewTh backBlue">
            @Html.DisplayNameFor(model => model.OwnerId)
        </dt>
        <dd class = "col-sm-9 viewTd backWhite">
            @Html.DisplayFor(model => model.Owner)
        </dd>
        <dt class = "col-sm-3 viewTh backBlue">
            @Html.DisplayNameFor(model => model.RunnerId)
        </dt>
        <dd class = "col-sm-9 viewTd backWhite">
            @Html.DisplayFor(model => model.Runner)
        </dd>
        <dt class = "col-sm-3 viewTh backBlue">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-9 viewTd backWhite">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-3 viewTh backBlue">
            @Html.DisplayNameFor(model => model.Instructions)
        </dt>
        <dd class = "col-sm-9 viewTd backWhite">
            @Html.DisplayFor(model => model.Instructions)
        </dd>
        <dt class = "col-sm-3 viewTh backBlue">
            @Html.DisplayNameFor(model => model.TimeIn)
        </dt>
        <dd class = "col-sm-9 viewTd backWhite">
            @Html.DisplayFor(model => model.TimeIn)
        </dd>
        <dt class = "col-sm-3 viewTh backBlue">
            @Html.DisplayNameFor(model => model.Deadline)
        </dt>
        <dd class = "col-sm-9 viewTd backWhite">
            @Html.DisplayFor(model => model.Deadline)
        </dd>
        <dt class = "col-sm-3 viewTh backBlue">
            @Html.DisplayNameFor(model => model.Started)
        </dt>
        <dd class = "col-sm-9 viewTd backWhite">
            @Html.DisplayFor(model => model.Started)
        </dd>
        <dt class = "col-sm-3 viewTh backBlue">
            @Html.DisplayNameFor(model => model.Executed)
        </dt>
        <dd class = "col-sm-9 viewTd backWhite">
            @Html.DisplayFor(model => model.Executed)
        </dd>
        <dt class = "col-sm-3 viewTh backBlue">
            @Html.DisplayNameFor(model => model.ExecutedNotes)
        </dt>
        <dd class = "col-sm-9 viewTd backWhite">
            @Html.DisplayFor(model => model.ExecutedNotes)
        </dd>
        <dt class = "col-sm-3 viewTh backBlue">
            @Html.DisplayNameFor(model => model.Completed)
        </dt>
        <dd class = "col-sm-9 viewTd backWhite">
            @Html.DisplayFor(model => model.Completed)
        </dd>
        <dt class = "col-sm-3 viewTh backBlue">
            @Html.DisplayNameFor(model => model.CompletionNotes)
        </dt>
        <dd class = "col-sm-9 viewTd backWhite">
            @Html.DisplayFor(model => model.CompletionNotes)
        </dd>
        <dt class = "col-sm-3 viewTh backBlue">
            @Html.DisplayNameFor(model => model.status)
        </dt>
        <dd class = "col-sm-9 viewTd backWhite">
            @Html.DisplayFor(model => model.status)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" class="cbtn cbtn-red" value="Delete" class="cbtn cbtn-red" />
        <input type="button" class="cbtn cbtn-plain" value="Back to List" onclick="location.href='@Url.Action("Index", "TaskAssignment")'" />
    </form>
</div>

Views/TaskAssignment/Details.cshtml
@model SmartOffice.Models.TaskAssignment

@{
    ViewData["Title"] = "Assignments";
}

@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery Xsrf
@functions{
    public string GetAntiXsrfRequestToken()
    {
        return Xsrf.GetAndStoreTokens(Context).RequestToken;
    }
}

<h2>@ViewData["Title"]</h2>

<div>
    @if (ViewBag.Editable == true)
    {
        <a class="clink clink-details" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
    }
    
    <a class="clink clink-edit" asp-action="Index">Back to List</a>
</div>

<hr />
<div class="details-container">
    <dl class="row" style="padding:  0 1% 0 1%;">
        <dt class = "col-sm-3 viewTh backBlue">
            @Html.DisplayNameFor(model => model.OwnerId)
        </dt>
        <dd class = "col-sm-9 viewTd backWhite">
            @Html.DisplayFor(model => model.Owner)
        </dd>
        <dt class = "col-sm-3 viewTh backBlue">
            @Html.DisplayNameFor(model => model.RunnerId)
        </dt>
        <dd class = "col-sm-9 viewTd backWhite">
            @Html.DisplayFor(model => model.Runner)
        </dd>
        <dt class = "col-sm-3 viewTh backBlue">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-9 viewTd backWhite">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-3 viewTh backBlue">
            @Html.DisplayNameFor(model => model.Instructions)
        </dt>
        <dd class = "col-sm-9 viewTd backWhite">
            @Html.DisplayFor(model => model.Instructions)
        </dd>
        <dt class = "col-sm-3 viewTh backBlue">
            @Html.DisplayNameFor(model => model.TimeIn)
        </dt>
        <dd class = "col-sm-9 viewTd backWhite">
            @Html.DisplayFor(model => model.TimeIn)
        </dd>
        <dt class = "col-sm-3 viewTh backBlue">
            @Html.DisplayNameFor(model => model.Deadline)
        </dt>
        <dd class = "col-sm-9 viewTd backWhite">
            @Html.DisplayFor(model => model.Deadline)
        </dd>
        <dt class = "col-sm-3 viewTh backBlue">
            @Html.DisplayNameFor(model => model.Started)
        </dt>
        <dd class = "col-sm-9 viewTd backWhite">
            @Html.DisplayFor(model => model.Started)
        </dd>
        <dt class = "col-sm-3 viewTh backBlue">
            @Html.DisplayNameFor(model => model.Executed)
        </dt>
        <dd class = "col-sm-9 viewTd backWhite">
            @Html.DisplayFor(model => model.Executed)
        </dd>
        <dt class = "col-sm-3 viewTh backBlue">
            @Html.DisplayNameFor(model => model.ExecutedNotes)
        </dt>
        <dd class = "col-sm-9 viewTd backWhite">
            @Html.DisplayFor(model => model.ExecutedNotes)
        </dd>
        <dt class = "col-sm-3 viewTh backBlue">
            @Html.DisplayNameFor(model => model.Completed)
        </dt>
        <dd class = "col-sm-9 viewTd backWhite">
            @Html.DisplayFor(model => model.Completed)
        </dd>
        <dt class = "col-sm-3 viewTh backBlue">
            @Html.DisplayNameFor(model => model.CompletionNotes)
        </dt>
        <dd class = "col-sm-9 viewTd backWhite">
            @Html.DisplayFor(model => model.CompletionNotes)
        </dd>
        <dt class = "col-sm-3 viewTh backBlue">
            @Html.DisplayNameFor(model => model.status)
        </dt>
        <dd class = "col-sm-9 viewTd backWhite">
            @Html.DisplayFor(model => model.status)
        </dd>
    </dl>
</div>

<div id="status-change-area" class="cflex">
    <div id="status-change-fields" style="display: none;">
        <form id="status-change-form">
            @if (Model.status == "completed")
            {
            }
            else
            {
                <input type="hidden" readonly id="Id" value="@Model.Id" />
                <input type="hidden" readonly id="OwnerId" value="@Model.OwnerId" />
                <input type="hidden" readonly id="RunnerId" value="@Model.RunnerId" />
                <input type="hidden" readonly id="Title" value="@Model.Title" />
                <input type="hidden" readonly id="Instructions" value="@Model.Instructions" />
                <input type="hidden" readonly id="TimeIn" value="@Model.TimeIn" />
                <input type="hidden" readonly id="Deadline" value="@Model.Deadline" />
                <input type="hidden" id="Started" value="@Model.Started" />
                <input type="hidden" id="Executed" value="@Model.Executed" />
                <div id="execute" style="display: none;">
                    <span class="cform-label">Notes</span><br/>
                    <textarea id="ExecutedNotes">@Model.ExecutedNotes</textarea><br/>
                </div>
                <input type="hidden" id="Completed" value="@Model.Completed" />
                <div id="complete" style="display: none;">
                    <span class="cform-label">Completion Notes</span><br/>
                    <textarea id="CompletionNotes">@Model.CompletionNotes</textarea><br/>
                </div>
                <input type="hidden" id="status" value="@Model.status" />
                <input type="hidden" id="__RequestVerificationToken" value="@GetAntiXsrfRequestToken()" />
                <div>
                    <input id="submit-btn" class="cbtn cbtn-blue" type="submit" value="Click to update status" />
                    <button class="cbtn cbtn-plain" onclick="endStatusUpdate();return false">Cancel</button>
                </div>
            }
        </form>
    </div>
    <input id="task-id" type="hidden" value="@Model.Id" />
    <input id="task-status" type="hidden" value="@Model.status" />
    <select id="status-changer">
        <option class="status-sel" value="default">Change the status of this task</option>
        @if (Model.status == "assigned")
        {
            <option class="status-sel" value="pending">Mark as Started</option>
        }
        @if (Model.status != "executed" && Model.status != "completed")
        {
            <option class="status-sel" value="executed">Mark as Executed</option>
        }
        @if (Model.status != "completed"
            && (ViewBag.Role == "special" || Model.OwnerId == ViewBag.CurrentUserId))
        {
            <option class="status-sel" value="completed">Mark as Completed</option>
        }
    </select>
</div>
<script src="~/js/assignmentStatusUpdate.js" asp-append-version="true"></script>

Views/TaskAssignment/Edit.cshtml
@model SmartOffice.Models.TaskAssignment

@{
    ViewData["Title"] = "Edit Assignment";
}

<h4>@ViewData["Title"]</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="hidden" asp-for="OwnerId" class="form-control" />
                <span asp-validation-for="OwnerId" class="text-danger"></span>
            </div>
            <div class="form-group" style="width: 45%;">
                <select asp-for="RunnerId" class="form-control">
                    <option value="">Who will execute this task?</option>
                    @foreach (var user in ViewBag.AllUsers)
                    {
                        <option value=@user.Id>@user.FullName</option>
                    }
                </select>
                <span asp-validation-for="RunnerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input style="width: 85%;" asp-for="Title" class="form-control" placeholder="Title" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <textarea style="width: 85%;" asp-for="Instructions" class="form-control"></textarea>
                <span asp-validation-for="Instructions" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="TimeIn" class="form-control" />
                <span asp-validation-for="TimeIn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Deadline" class="control-label"></label>
                <input style="width: 45%;" asp-for="Deadline" class="form-control" />
                <span asp-validation-for="Deadline" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="Started" class="form-control" />
                <span asp-validation-for="Started" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="Executed" class="form-control" />
                <span asp-validation-for="Executed" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="ExecutedNotes" class="form-control" />
                <span asp-validation-for="ExecutedNotes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="Completed" class="form-control" />
                <span asp-validation-for="Completed" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="CompletionNotes" class="form-control" />
                <span asp-validation-for="CompletionNotes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="status" class="form-control" />
                <span asp-validation-for="status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input class="cbtn cbtn-lemon" type="submit" value="Save" />
                <input type="button" class="cbtn cbtn-plain" value="Back to List" onclick="location.href='@Url.Action("Index", "TaskAssignment")'" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/TaskAssignment/Index.cshtml
@model X.PagedList.IPagedList<SmartOffice.Models.TaskAssignment>
@using X.PagedList.Mvc.Core;
@using X.PagedList;
@using X.PagedList.Mvc.Core.Fluent;
@using X.PagedList.Mvc.Core.Common;

@{
    ViewData["Title"] = "Assignments";
}

<h2>@ViewData["Title"]</h2>

<div class="cflex cflex-ends">
    <div>
        <input type="button" class="cbtn cbtn-lemon" value="Assign a Task" onclick="location.href='@Url.Action("Create", "TaskAssignment")'" />
    </div>
    <div>
        <form asp-controller="TaskAssignment" asp-action="Index" method="get">
            <input type="text" style="width: 400px; border: 1px solid lightgray" class="npt-text" name="SearchString" placeholder="Firstname Lastname (Case Sensitive)">
            <input type="submit" class="cbtn cbtn-plain" id="taskFilter" value="Filter assignments" />
        </form>
    </div>
</div>

<table class="ctable">
    <thead>
        <tr>
            <th>
                @Html.ActionLink("Assignee", "Index", new { sortOrder = ViewBag.RunnerSortParm, currentFilter=ViewBag.CurrentFilter }, new { @class = "cbtn-sort"})
            </th>
            <th>
                Title
            </th>
            <th>
                @Html.ActionLink("Submitted", "Index", new { sortOrder = ViewBag.TimeSortParm, currentFilter=ViewBag.CurrentFilter }, new { @class = "cbtn-sort"})
            </th>
            <th>
                @Html.ActionLink("Deadline", "Index", new { sortOrder = ViewBag.DeadlineSortParm, currentFilter=ViewBag.CurrentFilter }, new { @class = "cbtn-sort"})
            </th>
            <th>
                Status
            </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Runner)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TimeIn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Deadline)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.status)
            </td>
            <td style="white-space: nowrap">
                @if ((string) ViewData["idOfCurrentUser"] == item.OwnerId
                    && (item.status == "assigned"
                    || item.status == "pending"
                    || item.status == "overdue"))
                {
                    <a class="clink clink-edit" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                }

                <a class="clink clink-details" asp-action="Details" asp-route-id="@item.Id">Details</a>
                
                @if ((string) ViewData["idOfCurrentUser"] == item.OwnerId
                    && (item.status == "assigned"
                    || item.status == "pending"
                    || item.status == "overdue"))
                {
                    <a class="clink clink-delete" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                }
            </td>
        </tr>
}
    </tbody>
</table>
<br/>
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index", 
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }),
    new PagedListRenderOptions()
    {
        ContainerDivClasses = new [] { "cbtn-pager" },
        LiElementClasses = new List<string> {"cbtn-pager-list", "another-class"},
        PageClasses = new string[] { "cbtn-pager-pages" }
    })