Models/ApplicationUser.cs
using System;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Identity;

namespace SmartOffice.Models
{
    public class ApplicationUser : IdentityUser
    { 
        [Required]
        [MaxLength(50)]
        [Display(Name = "First name")]
        public string FirstName { get; set; }

        [Required]
        [MaxLength(50)]
        [Display(Name = "Last name")]
        public string LastName { get; set; }

        public string FullName;
    }
}

Controllers/ApplicationUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SmartOffice.Data;
using SmartOffice.Models;
using Microsoft.AspNetCore.Authorization;
using BC = BCrypt.Net.BCrypt;
using System.Security.Cryptography;
using Microsoft.AspNetCore.Cryptography.KeyDerivation;

namespace SmartOffice.Controllers
{
    [Authorize(Roles ="superuser,admin")]
    public class ApplicationUserController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ApplicationUserController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ApplicationUser
        public ViewResult Index()
        {
            var applicationUsers = from s in _context.Users
                select new ApplicationUser
                {
                    Id = s.Id,
                    FirstName = s.FirstName,
                    LastName = s.LastName,
                    Email = s.Email,
                    PhoneNumber = s.PhoneNumber
                };
            return View(applicationUsers);
        }

        // GET: ApplicationUser/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationUser = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (applicationUser == null)
            {
                return NotFound();
            }

            return View(applicationUser);
        }

/*
        // GET: ApplicationUser/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ApplicationUser/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FirstName,LastName,Id,UserName,NormalizedUserName,Email,NormalizedEmail,EmailConfirmed,PasswordHash,SecurityStamp,ConcurrencyStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEnd,LockoutEnabled,AccessFailedCount")] ApplicationUser applicationUser)
        {
            //applicationUser.PasswordHash = BC.HashPassword(applicationUser.PasswordHash);
            applicationUser.EmailConfirmed = true;
            applicationUser.LockoutEnabled = true;
            applicationUser.UserName = applicationUser.Email;

            byte[] salt = new byte[128 / 8];
            using (var rng = RandomNumberGenerator.Create())
            {
                rng.GetBytes(salt);
            }
            applicationUser.PasswordHash = Convert.ToBase64String(KeyDerivation.Pbkdf2(
                password: applicationUser.PasswordHash,
                salt: salt,
                prf: KeyDerivationPrf.HMACSHA1,
                iterationCount: 10000,
                numBytesRequested: 256 / 8));

            if (ModelState.IsValid)
            {
                _context.Add(applicationUser);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(applicationUser);
        }

        // GET: ApplicationUser/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationUser = await _context.Users.FindAsync(id);
            if (applicationUser == null)
            {
                return NotFound();
            }
            return View(applicationUser);
        }

        // POST: ApplicationUser/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("FirstName,LastName,Id,UserName,NormalizedUserName,Email,NormalizedEmail,EmailConfirmed,PasswordHash,SecurityStamp,ConcurrencyStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEnd,LockoutEnabled,AccessFailedCount")] ApplicationUser applicationUser)
        {
            if (id != applicationUser.Id)
            {
                return NotFound();
            }

            applicationUser.UserName = applicationUser.Email;

            byte[] salt = new byte[128 / 8];
            using (var rng = RandomNumberGenerator.Create())
            {
                rng.GetBytes(salt);
            }
            applicationUser.PasswordHash = Convert.ToBase64String(KeyDerivation.Pbkdf2(
                password: applicationUser.PasswordHash,
                salt: salt,
                prf: KeyDerivationPrf.HMACSHA1,
                iterationCount: 10000,
                numBytesRequested: 256 / 8));

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(applicationUser);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ApplicationUserExists(applicationUser.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(applicationUser);
        }

        // GET: ApplicationUser/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationUser = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (applicationUser == null)
            {
                return NotFound();
            }

            return View(applicationUser);
        }

        // POST: ApplicationUser/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var applicationUser = await _context.Users.FindAsync(id);
            _context.Users.Remove(applicationUser);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ApplicationUserExists(string id)
        {
            return _context.Users.Any(e => e.Id == id);
        }
*/  
    }
}

Views/ApplicationUser/Create.cshtml
@model SmartOffice.Models.ApplicationUser

@{
    ViewData["Title"] = "Create a new user";
}

<h4>@ViewData["Title"]</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input style="width: 75%;" asp-for="FirstName" class="form-control" placeholder="First Name" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input style="width: 75%;" asp-for="LastName" class="form-control" placeholder="Last Name" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input style="width: 75%;" asp-for="Email" class="form-control" placeholder="Email" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input style="width: 75%;" asp-for="PasswordHash" type="password" class="form-control" placeholder="Password" />
            </div>
            <div class="form-group">
                <input style="width: 75%;" asp-for="PhoneNumber" class="form-control" placeholder="Telephone" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input class="cbtn cbtn-lemon" type="submit" value="Create User" />
                <input type="button" class="cbtn cbtn-plain" value="Back to List" onclick="location.href='@Url.Action("Index", "ApplicationUser")'" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/ApplicationUser/Delete.cshtml
@model SmartOffice.Models.ApplicationUser

@{
    ViewData["Title"] = "Delete";
}

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="row" style="padding: 1%;">
        <dt class = "col-sm-3 viewTh backBlue">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-9 viewTd backWhite">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-3 viewTh backBlue">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-9 viewTd backWhite">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-3 viewTh backBlue">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class = "col-sm-9 viewTd backWhite">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class = "col-sm-3 viewTh backBlue">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-9 viewTd backWhite">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-3 viewTh backBlue">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-9 viewTd backWhite">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" class="cbtn cbtn-red" value="Delete" class="btn btn-danger" />
        <input type="button" class="cbtn cbtn-plain" value="Back to List" onclick="location.href='@Url.Action("Index", "ApplicationUser")'" />
    </form>
</div>

Views/ApplicationUser/Details.cshtml
@model SmartOffice.Models.ApplicationUser

@{
    ViewData["Title"] = "Users";
}

<h2>@ViewData["Title"]</h2>

<div>
    <a class="clink clink-details" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
    <a class="clink clink-edit" asp-action="Index">Back to List</a>
</div>

<hr />
<div class="details-container">
    <dl class="row" style="padding:  0 1% 0 1%;">
        <dt class = "col-sm-3 viewTh backBlue">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-9 viewTd backWhite">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-3 viewTh backBlue">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-9 viewTd backWhite">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-3 viewTh backBlue">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class = "col-sm-9 viewTd backWhite">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class = "col-sm-3 viewTh backBlue">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-9 viewTd backWhite">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-3 viewTh backBlue">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-9 viewTd backWhite">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
    </dl>
</div>

Views/ApplicationUser/Edit.cshtml
@model SmartOffice.Models.ApplicationUser

@{
    ViewData["Title"] = "Edit User";
}


<h4>@ViewData["Title"]</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input style="width: 75%;" asp-for="FirstName" class="form-control" placeholder="First Name" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input style="width: 75%;" asp-for="LastName" class="form-control" placeholder="Last Namae" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="hidden" asp-for="NormalizedUserName" class="form-control" />
            </div>
            <div class="form-group">
                <input style="width: 75%;" asp-for="Email" class="form-control" placeholder="Email" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="NormalizedEmail" class="form-control" />
            </div>
            <div class="form-group form-check">
                    <input type="hidden" class="form-check-input" asp-for="EmailConfirmed" />
            </div>
            <div class="form-group">
                <input type="password" style="width: 75%;" asp-for="PasswordHash" class="form-control" placeholder="Password" />
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="SecurityStamp" class="form-control" />
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="ConcurrencyStamp" class="form-control" />
            </div>
            <div class="form-group">
                <input style="width: 75%;" asp-for="PhoneNumber" class="form-control" placeholder="Telephone" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                    <input type="hidden" class="form-check-input" asp-for="PhoneNumberConfirmed" />
            </div>
            <div class="form-group form-check">
                    <input type="hidden" class="form-check-input" asp-for="TwoFactorEnabled" />
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="LockoutEnd" class="form-control" />
            </div>
            <div class="form-group form-check">
                    <input type="hidden" class="form-check-input" asp-for="LockoutEnabled" />
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="AccessFailedCount" class="form-control" />
            </div>
            <div class="form-group">
                <input class="cbtn cbtn-lemon" type="submit" value="Save" />
                <input type="button" class="cbtn cbtn-plain" value="Back to List" onclick="location.href='@Url.Action("Index", "ApplicationUser")'" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/ApplicationUser/Index.cshtml
@model IEnumerable<SmartOffice.Models.ApplicationUser>

@{
    ViewData["Title"] = "Users";
}

<h2>@ViewData["Title"]</h2>

<div class="cflex cflex-ends">
    <div>
        <input type="button" class="cbtn cbtn-lemon" value="Create New User" onclick="location.href='@Url.Action("Create", "ApplicationUser")'" />
    </div>
    <div>
    </div>
</div>
<table class="ctable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td style="white-space: nowrap">
                <a class="clink clink-edit" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                <a class="clink clink-details" asp-action="Details" asp-route-id="@item.Id">Details</a>
                <a class="clink clink-delete"  asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>